export default {
  "Group A": [
    {
      round: 1,
      date: "2022-11-20 16:00:00Z",
      location: "Al Bayt Stadium",
      home: "Qatar",
      away: "Ecuador",
      matchNumber: 1,
    },
    {
      round: 1,
      date: "2022-11-21 16:00:00Z",
      location: "Al Thumama Stadium",
      home: "Senegal",
      away: "Netherlands",
      matchNumber: 2,
    },
    {
      round: 2,
      date: "2022-11-25 13:00:00Z",
      location: "Al Thumama Stadium",
      home: "Qatar",
      away: "Senegal",
      matchNumber: 18,
    },
    {
      round: 2,
      date: "2022-11-25 16:00:00Z",
      location: "Khalifa International Stadium",
      home: "Netherlands",
      away: "Ecuador",
      matchNumber: 19,
    },
    {
      round: 3,
      date: "2022-11-29 15:00:00Z",
      location: "Khalifa International Stadium",
      home: "Ecuador",
      away: "Senegal",
      matchNumber: 35,
    },
    {
      round: 3,
      date: "2022-11-29 15:00:00Z",
      location: "Al Bayt Stadium",
      home: "Netherlands",
      away: "Qatar",
      matchNumber: 36,
    },
  ],
  "Group B": [
    {
      round: 1,
      date: "2022-11-21 13:00:00Z",
      location: "Khalifa International Stadium",
      home: "England",
      away: "Iran",
      matchNumber: 3,
    },
    {
      round: 1,
      date: "2022-11-21 19:00:00Z",
      location: "Ahmad Bin Ali Stadium",
      home: "USA",
      away: "Wales",
      matchNumber: 4,
    },
    {
      round: 2,
      date: "2022-11-25 10:00:00Z",
      location: "Ahmad Bin Ali Stadium",
      home: "Wales",
      away: "Iran",
      matchNumber: 17,
    },
    {
      round: 2,
      date: "2022-11-25 19:00:00Z",
      location: "Al Bayt Stadium",
      home: "England",
      away: "USA",
      matchNumber: 20,
    },
    {
      round: 3,
      date: "2022-11-29 19:00:00Z",
      location: "Ahmad Bin Ali Stadium",
      home: "Wales",
      away: "England",
      matchNumber: 33,
    },
    {
      round: 3,
      date: "2022-11-29 19:00:00Z",
      location: "Al Thumama Stadium",
      home: "Iran",
      away: "USA",
      matchNumber: 34,
    },
  ],
  "Group C": [
    {
      round: 1,
      date: "2022-11-22 16:00:00Z",
      location: "Stadium 974",
      home: "Mexico",
      away: "Poland",
      matchNumber: 7,
    },
    {
      round: 1,
      date: "2022-11-22 10:00:00Z",
      location: "Lusail Stadium",
      home: "Argentina",
      away: "Saudi Arabia",
      matchNumber: 8,
    },
    {
      round: 2,
      date: "2022-11-26 13:00:00Z",
      location: "Education City Stadium",
      home: "Poland",
      away: "Saudi Arabia",
      matchNumber: 22,
    },
    {
      round: 2,
      date: "2022-11-26 19:00:00Z",
      location: "Lusail Stadium",
      home: "Argentina",
      away: "Mexico",
      matchNumber: 24,
    },
    {
      round: 3,
      date: "2022-11-30 19:00:00Z",
      location: "Stadium 974",
      home: "Poland",
      away: "Argentina",
      matchNumber: 39,
    },
    {
      round: 3,
      date: "2022-11-30 19:00:00Z",
      location: "Lusail Stadium",
      home: "Saudi Arabia",
      away: "Mexico",
      matchNumber: 40,
    },
  ],
  "Group D": [
    {
      round: 1,
      date: "2022-11-22 19:00:00Z",
      location: "Al Janoub Stadium",
      home: "France",
      away: "Australia",
      matchNumber: 5,
    },
    {
      round: 1,
      date: "2022-11-22 13:00:00Z",
      location: "Education City Stadium",
      home: "Denmark",
      away: "Tunisia",
      matchNumber: 6,
    },
    {
      round: 2,
      date: "2022-11-26 10:00:00Z",
      location: "Al Janoub Stadium",
      home: "Tunisia",
      away: "Australia",
      matchNumber: 21,
    },
    {
      round: 2,
      date: "2022-11-26 16:00:00Z",
      location: "Stadium 974",
      home: "France",
      away: "Denmark",
      matchNumber: 23,
    },
    {
      round: 3,
      date: "2022-11-30 15:00:00Z",
      location: "Al Janoub Stadium",
      home: "Australia",
      away: "Denmark",
      matchNumber: 37,
    },
    {
      round: 3,
      date: "2022-11-30 15:00:00Z",
      location: "Education City Stadium",
      home: "Tunisia",
      away: "France",
      matchNumber: 38,
    },
  ],
  "Group F": [
    {
      round: 1,
      date: "2022-11-23 19:00:00Z",
      location: "Ahmad Bin Ali Stadium",
      home: "Belgium",
      away: "Canada",
      matchNumber: 9,
    },
    {
      round: 1,
      date: "2022-11-23 10:00:00Z",
      location: "Al Bayt Stadium",
      home: "Morocco",
      away: "Croatia",
      matchNumber: 12,
    },
    {
      round: 2,
      date: "2022-11-27 13:00:00Z",
      location: "Al Thumama Stadium",
      home: "Belgium",
      away: "Morocco",
      matchNumber: 26,
    },
    {
      round: 2,
      date: "2022-11-27 16:00:00Z",
      location: "Khalifa International Stadium",
      home: "Croatia",
      away: "Canada",
      matchNumber: 27,
    },
    {
      round: 3,
      date: "2022-12-01 15:00:00Z",
      location: "Ahmad Bin Ali Stadium",
      home: "Croatia",
      away: "Belgium",
      matchNumber: 41,
    },
    {
      round: 3,
      date: "2022-12-01 15:00:00Z",
      location: "Al Thumama Stadium",
      home: "Canada",
      away: "Morocco",
      matchNumber: 42,
    },
  ],
  "Group E": [
    {
      round: 1,
      date: "2022-11-23 16:00:00Z",
      location: "Al Thumama Stadium",
      home: "Spain",
      away: "Costa Rica",
      matchNumber: 10,
    },
    {
      round: 1,
      date: "2022-11-23 13:00:00Z",
      location: "Khalifa International Stadium",
      home: "Germany",
      away: "Japan",
      matchNumber: 11,
    },
    {
      round: 2,
      date: "2022-11-27 10:00:00Z",
      location: "Ahmad Bin Ali Stadium",
      home: "Japan",
      away: "Costa Rica",
      matchNumber: 25,
    },
    {
      round: 2,
      date: "2022-11-27 19:00:00Z",
      location: "Al Bayt Stadium",
      home: "Spain",
      away: "Germany",
      matchNumber: 28,
    },
    {
      round: 3,
      date: "2022-12-01 19:00:00Z",
      location: "Khalifa International Stadium",
      home: "Japan",
      away: "Spain",
      matchNumber: 43,
    },
    {
      round: 3,
      date: "2022-12-01 19:00:00Z",
      location: "Al Bayt Stadium",
      home: "Costa Rica",
      away: "Germany",
      matchNumber: 44,
    },
  ],
  "Group G": [
    {
      round: 1,
      date: "2022-11-24 10:00:00Z",
      location: "Al Janoub Stadium",
      home: "Switzerland",
      away: "Cameroon",
      matchNumber: 13,
    },
    {
      round: 1,
      date: "2022-11-24 19:00:00Z",
      location: "Lusail Stadium",
      home: "Brazil",
      away: "Serbia",
      matchNumber: 16,
    },
    {
      round: 2,
      date: "2022-11-28 10:00:00Z",
      location: "Al Janoub Stadium",
      home: "Cameroon",
      away: "Serbia",
      matchNumber: 29,
    },
    {
      round: 2,
      date: "2022-11-28 16:00:00Z",
      location: "Stadium 974",
      home: "Brazil",
      away: "Switzerland",
      matchNumber: 31,
    },
    {
      round: 3,
      date: "2022-12-02 19:00:00Z",
      location: "Stadium 974",
      home: "Serbia",
      away: "Switzerland",
      matchNumber: 47,
    },
    {
      round: 3,
      date: "2022-12-02 19:00:00Z",
      location: "Lusail Stadium",
      home: "Cameroon",
      away: "Brazil",
      matchNumber: 48,
    },
  ],
  "Group H": [
    {
      round: 1,
      date: "2022-11-24 13:00:00Z",
      location: "Education City Stadium",
      home: "Uruguay",
      away: "Korea Republic",
      matchNumber: 14,
    },
    {
      round: 1,
      date: "2022-11-24 16:00:00Z",
      location: "Stadium 974",
      home: "Portugal",
      away: "Ghana",
      matchNumber: 15,
    },
    {
      round: 2,
      date: "2022-11-28 13:00:00Z",
      location: "Education City Stadium",
      home: "Korea Republic",
      away: "Ghana",
      matchNumber: 30,
    },
    {
      round: 2,
      date: "2022-11-28 19:00:00Z",
      location: "Lusail Stadium",
      home: "Portugal",
      away: "Uruguay",
      matchNumber: 32,
    },
    {
      round: 3,
      date: "2022-12-02 15:00:00Z",
      location: "Al Janoub Stadium",
      home: "Ghana",
      away: "Uruguay",
      matchNumber: 45,
    },
    {
      round: 3,
      date: "2022-12-02 15:00:00Z",
      location: "Education City Stadium",
      home: "Korea Republic",
      away: "Portugal",
      matchNumber: 46,
    },
  ],
};
